default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spree_store_development

test:
  <<: *default
  database: spree_store_test

production:
  <<: *default
  database: spree_store_production
  username: spree_store
  password: <%= ENV['NELOU_DATABASE_PASSWORD'] %>
